repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E203,W503", "--per-file-ignores=test_*.py:C901"]
        additional_dependencies: []
  - repo: local
    hooks:
      - id: eslint-server
        name: eslint (server)
        entry: bash -lc "cd server && npm run lint"
        language: system
        types: ["ts"]
        pass_filenames: false
