name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  typescript-tests:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
    
    - name: Run linter
      run: |
        cd server
        npm run lint
    
    - name: Type check
      run: |
        cd server
        npm run typecheck
    
    - name: Run tests
      run: |
        cd server
        npm run test:coverage
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./server/coverage/lcov.info
        flags: typescript

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        # Use Python 3.11 to match Unreal Engine 5.4+ built-in Python version
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
    
    - name: Run linter
      run: |
        cd python
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Run type checker
      run: |
        cd python
        mypy . --ignore-missing-imports
    
    - name: Run tests
      run: |
        python -m pytest python/tests/ --cov=python --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: python

  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: [typescript-tests, python-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Build TypeScript
      run: |
        cd server
        npm ci
        npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: server-dist
        path: server/dist/

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: server-dist
        path: server/dist/
    
    - name: Setup test environment
      run: |
        echo "Setting up integration test environment"
        # Add integration test setup here
    
    - name: Run integration tests
      run: |
        echo "Running integration tests"
        # Add integration tests here