name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install and Build
      run: |
        cd server
        npm ci
        npm run build
    
    - name: Package Server
      run: |
        cd server
        tar -czf ../uemcp-server-${{ github.ref_name }}.tar.gz dist/ package.json package-lock.json
    
    - name: Package Plugin
      run: |
        # Create plugin directory structure
        mkdir -p UEMCP-Plugin/UEMCP
        
        # Copy plugin files
        cp -r plugin/* UEMCP-Plugin/UEMCP/
        
        # Create zip
        cd UEMCP-Plugin
        zip -r ../UEMCP-Plugin-${{ github.ref_name }}.zip UEMCP/
        cd ..
    
    - name: Create Full Package
      run: |
        # Create full package directory
        mkdir -p UEMCP-Full-${{ github.ref_name }}
        
        # Copy all components
        cp -r server UEMCP-Full-${{ github.ref_name }}/
        cp -r plugin UEMCP-Full-${{ github.ref_name }}/
        cp -r docs UEMCP-Full-${{ github.ref_name }}/
        cp README.md CLAUDE.md PLAN.md RELEASE_PROCESS.md UEMCP-Full-${{ github.ref_name }}/
        
        # Copy LICENSE if it exists
        if [ -f LICENSE ]; then
          cp LICENSE UEMCP-Full-${{ github.ref_name }}/
        fi
        
        # Copy setup scripts
        cp setup.sh UEMCP-Full-${{ github.ref_name }}/
        
        # Create zip
        zip -r UEMCP-Full-${{ github.ref_name }}.zip UEMCP-Full-${{ github.ref_name }}/
    
    - name: Generate Checksums
      run: |
        sha256sum *.tar.gz *.zip > checksums-${{ github.ref_name }}.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          uemcp-server-${{ github.ref_name }}.tar.gz
          UEMCP-Plugin-${{ github.ref_name }}.zip
          UEMCP-Full-${{ github.ref_name }}.zip
          checksums-${{ github.ref_name }}.txt
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
        body: |
          ## UEMCP ${{ github.ref_name }}
          
          ### Installation
          
          #### Quick Start (Recommended)
          Download `UEMCP-Full-${{ github.ref_name }}.zip` and run:
          ```bash
          unzip UEMCP-Full-${{ github.ref_name }}.zip
          cd UEMCP-Full-${{ github.ref_name }}
          ./setup.sh
          ```
          
          #### Individual Components
          - **Plugin only**: `UEMCP-Plugin-${{ github.ref_name }}.zip`
          - **Server only**: `uemcp-server-${{ github.ref_name }}.tar.gz`
          
          ### What's Changed
          See below for full changelog.
          
          ### Checksums
          Verify downloads with `checksums-${{ github.ref_name }}.txt`